In [58]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler

from sklearn.tree import DecisionTreeClassifier

from sklearn.ensemble import RandomForestClassifier

from sklearn.neighbors import KNeighborsClassifier

from xgboost import XGBClassifier

from sklearn.metrics import accuracy_score

from sklearn.metrics import confusion_matrix

from sklearn.metrics import classification_report

import joblib

In [59]:
df = pd.read_excel("../datasets/rainfall_in_india_1901_2015.xlsx")

In [60]:
df.head()

,COUNTRY,STATE,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,Jan-Feb,Mar-May,Jun-Sep,Oct-Dec
0,India,ANDAMAN & NICOBAR ISLANDS,1901,49.2,87.1,29.2,2.3,528.8,517.5,365.1,481.1,332.6,388.5,558.2,33.6,3373.2,136.3,560.3,1696.3,980.3
1,India,ANDAMAN & NICOBAR ISLANDS,1902,0.0,159.8,12.2,0.0,446.1,537.1,228.9,753.7,666.2,197.2,359.0,160.5,3520.7,159.8,458.3,2185.9,716.7
2,India,ANDAMAN & NICOBAR ISLANDS,1903,12.7,144.0,0.0,1.0,235.1,479.9,728.4,326.7,339.0,181.2,284.4,225.0,2957.4,156.7,236.1,1874.0,690.6
3,India,ANDAMAN & NICOBAR ISLANDS,1904,9.4,14.7,0.0,202.4,304.5,495.1,502.0,160.1,820.4,222.2,308.7,40.1,3079.6,24.1,506.9,1977.6,571.0
4,India,ANDAMAN & NICOBAR ISLANDS,1905,1.3,0.0,3.3,26.9,279.5,628.7,368.7,330.5,297.0,260.7,25.4,344.7,2566.7,1.3,309.7,1624.9,630.8

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4116 entries, 0 to 4115
Data columns (total 20 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   COUNTRY  4116 non-null   object
 1   STATE    4116 non-null   object
 2   YEAR     4116 non-null   int64
 3   JAN      4112 non-null   float64
 4   FEB      4113 non-null   float64
 5   MAR      4110 non-null   float64
 6   APR      4112 non-null   float64
 7   MAY      4113 non-null   float64
 8   JUN      4111 non-null   float64
 9   JUL      4109 non-null   float64
 10  AUG      4112 non-null   float64
 11  SEP      4110 non-null   float64
 12  OCT      4109 non-null   float64
 13  NOV      4105 non-null   float64
 14  DEC      4106 non-null   float64
 15  ANNUAL   4090 non-null   float64
 16  Jan-Feb  4110 non-null   float64
 17  Mar-May  4107 non-null   float64
 18  Jun-Sep  4106 non-null   float64
 19  Oct-Dec  4103 non-null   float64
dtypes: float64(17), int64(1), object(2)
memory usage: 643.2+ KB

In [62]:
df.isnull().sum()

COUNTRY     0
STATE       0
YEAR        0
JAN         4
FEB         3
MAR         6
APR         4
MAY         3
JUN         5
JUL         7
AUG         4
SEP         6
OCT         7
NOV        11
DEC        10
ANNUAL     26
Jan-Feb     6
Mar-May     9
Jun-Sep    10
Oct-Dec    13
dtype: int64

In [63]:
df.shape

(4116, 20)

In [64]:
df.columns

Index(['COUNTRY', 'STATE', 'YEAR', 'JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN',
       'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC', 'ANNUAL', 'Jan-Feb',
       'Mar-May', 'Jun-Sep', 'Oct-Dec'],
      dtype='object')

In [65]:
df.describe()

,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,Jan-Feb,Mar-May,Jun-Sep,Oct-Dec
count,4116.000000,4112.000000,4113.000000,4110.000000,4112.000000,4113.000000,4111.000000,4109.000000,4112.000000,4110.000000,4109.000000,4105.000000,4106.000000,4090.000000,4110.000000,4107.000000,4106.000000,4103.000000
mean,1958.218659,18.957320,21.805325,27.359197,43.127432,85.745417,230.234444,347.214334,290.263497,197.361922,95.507009,39.866163,18.870580,1411.008900,40.747786,155.901753,1064.724769,154.100487
std,33.140898,33.585371,35.909488,46.959424,67.831168,123.234904,234.710758,269.539667,188.770477,135.408345,99.519134,68.685410,42.369611,903.846565,59.308277,201.316965,707.741531,166.942660
min,1901.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.400000,0.000000,0.000000,0.100000,0.000000,0.000000,0.000000,62.300000,0.000000,0.000000,57.400000,0.000000
25%,1930.000000,0.600000,0.600000,1.000000,3.000000,8.600000,70.350000,175.600000,155.975000,100.525000,14.600000,0.700000,0.100000,804.500000,4.100000,24.050000,573.850000,34.200000
50%,1958.000000,6.000000,6.700000,7.800000,15.700000,36.600000,138.700000,284.800000,259.400000,173.900000,65.200000,9.500000,3.000000,1121.300000,19.200000,74.800000,881.100000,98.200000
75%,1987.000000,22.200000,26.800000,31.300000,49.950000,97.200000,305.150000,418.400000,377.800000,265.800000,148.400000,46.100000,17.500000,1644.775000,50.375000,196.950000,1288.175000,213.500000
max,2015.000000,583.700000,403.500000,605.600000,595.100000,1168.600000,1609.900000,2362.800000,1664.600000,1222.000000,948.300000,648.900000,617.500000,6331.100000,699.500000,1745.800000,4536.900000,1252.500000

In [66]:
df.fillna(df.mean(numeric_only=True), inplace=True)

In [67]:
df.isnull().sum()

COUNTRY    0
STATE      0
YEAR       0
JAN        0
FEB        0
MAR        0
APR        0
MAY        0
JUN        0
JUL        0
AUG        0
SEP        0
OCT        0
NOV        0
DEC        0
ANNUAL     0
Jan-Feb    0
Mar-May    0
Jun-Sep    0
Oct-Dec    0
dtype: int64

In [68]:
df["Flood"] = (df["ANNUAL"] >= 2500).astype(int)

In [69]:
print(df["Flood"].value_counts())

Flood
0    3443
1     673
Name: count, dtype: int64

In [70]:
X = df.drop(["COUNTRY", "STATE", "YEAR", "ANNUAL", "Flood"], axis=1)
y = df["Flood"]

In [71]:
print(X.shape)
print(y.shape)

(4116, 16)
(4116,)

In [72]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [73]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(3292, 16)
(824, 16)
(3292,)
(824,)

In [74]:
print(X.columns)

Index(['JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT',
       'NOV', 'DEC', 'Jan-Feb', 'Mar-May', 'Jun-Sep', 'Oct-Dec'],
      dtype='object')

In [75]:
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(random_state=42)

dt_model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [76]:
dt_pred = dt_model.predict(X_test)

print("Decision Tree Accuracy:", accuracy_score(y_test, dt_pred))

Decision Tree Accuracy: 0.9793689320388349

In [77]:
print(confusion_matrix(y_test, dt_pred))

[[681   8]
 [  9 126]]

In [78]:
print(classification_report(y_test, dt_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       689
           1       0.94      0.93      0.94       135

    accuracy                           0.98       824
   macro avg       0.96      0.96      0.96       824
weighted avg       0.98      0.98      0.98       824

In [79]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf_model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [80]:
rf_pred = rf_model.predict(X_test)

print("Random Forest Accuracy:", accuracy_score(y_test, rf_pred))

Random Forest Accuracy: 0.9902912621359223

In [81]:
print(confusion_matrix(y_test, rf_pred))

[[685   4]
 [  4 131]]

In [82]:
print(classification_report(y_test, rf_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       689
           1       0.97      0.97      0.97       135

    accuracy                           0.99       824
   macro avg       0.98      0.98      0.98       824
weighted avg       0.99      0.99      0.99       824

In [83]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

In [84]:
from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(n_neighbors=5)

knn_model.fit(X_train_scaled, y_train)

KNeighborsClassifier()

In [85]:
knn_pred = knn_model.predict(X_test_scaled)

print("KNN Accuracy:", accuracy_score(y_test, knn_pred))

KNN Accuracy: 0.9769417475728155

In [86]:
print(confusion_matrix(y_test, knn_pred))

[[681   8]
 [ 11 124]]

In [88]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    random_state=42,
    eval_metric="logloss"
)

xgb_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, random_state=42, ...)

In [89]:
xgb_pred = xgb_model.predict(X_test)

print("XGBoost Accuracy:", accuracy_score(y_test, xgb_pred))

XGBoost Accuracy: 0.9890776699029126

In [90]:
print(confusion_matrix(y_test, xgb_pred))

[[684   5]
 [  4 131]]

In [91]:
print(classification_report(y_test, xgb_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       689
           1       0.96      0.97      0.97       135

    accuracy                           0.99       824
   macro avg       0.98      0.98      0.98       824
weighted avg       0.99      0.99      0.99       824

In [92]:
results = {
    "Model": [
        "Decision Tree",
        "Random Forest",
        "KNN",
        "XGBoost"
    ],
    "Accuracy": [
        accuracy_score(y_test, dt_pred),
        accuracy_score(y_test, rf_pred),
        accuracy_score(y_test, knn_pred),
        accuracy_score(y_test, xgb_pred)
    ]
}

results_df = pd.DataFrame(results)

results_df.sort_values(by="Accuracy", ascending=False)

           Model  Accuracy
1  Random Forest  0.990291
3        XGBoost  0.989078
0  Decision Tree  0.979369
2            KNN  0.976942

In [93]:
import joblib

joblib.dump(rf_model, "../model/model.pkl")

joblib.dump(scaler, "../model/scaler.pkl")

print("Random Forest Model Saved Successfully")

Random Forest Model Saved Successfully

In [94]:
model = joblib.load("../model/model.pkl")

print(type(model))

<class 'sklearn.ensemble._forest.RandomForestClassifier'>

In [95]:
print(X.columns.tolist())
print(len(X.columns))

['JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC', 'Jan-Feb', 'Mar-May', 'Jun-Sep', 'Oct-Dec']
16